parent=keycloak.v2

styles=css/styles.css css/nerva-tokens.css css/banking-login.css
scripts=js/banking-login.js

locales=es
darkMode=false

bankingFrontendUrl=${env.BANKING_FRONTEND_URL\:http://localhost:4200}

kcHtmlClass=banking-login
kcBodyClass=banking-login__body
