---
global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
  scrape_native_histograms: true

otlp:
  keep_identifying_resource_attributes: true
  promote_resource_attributes:
    - service.instance.id
    - service.name
    - service.namespace
    - service.version
    - deployment.environment
    - deployment.environment.name

storage:
  tsdb:
    out_of_order_time_window: 10m

scrape_configs:
  - job_name: api-gateway
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:8085"]

  - job_name: home-banking-bff
    metrics_path: /web/actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:8086"]

  - job_name: onboarding-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:8087"]

  - job_name: notification-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:8083"]
