spring:
  datasource:
    url: ${ACCOUNT_DB_URL:jdbc:mysql://localhost:3308/account_db}
    username: ${ACCOUNT_DB_USERNAME:account_user}
    password: ${ACCOUNT_DB_PASSWORD:account_password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  security:
    oauth2:
      client:
        registration:
          account-service:
            provider: keycloak
            client-id: ${ACCOUNT_INTERNAL_OAUTH_CLIENT_ID:account-service}
            client-secret: ${ACCOUNT_INTERNAL_OAUTH_CLIENT_SECRET:local-account-secret}
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8090/realms/banking-ecosystem}
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8090/realms/banking-ecosystem}

server:
  port: ${ACCOUNT_SERVICE_PORT:8081}

banking:
  identifiers:
    bank-code: ${BANK_CODE:285}
    default-branch-code: ${DEFAULT_BRANCH_CODE:0001}
  security:
    public-docs-enabled: ${PUBLIC_DOCS_ENABLED:true}

eureka:
  client:
    enabled: ${EUREKA_CLIENT_ENABLED:true}
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    oauth:
      client-id: ${SWAGGER_OAUTH_CLIENT_ID:banking-swagger}
      use-pkce-with-authorization-code-grant: true

info:
  app:
    name: account-service
    description: Account service for banking accounts and operational balances
    version: 0.0.1-SNAPSHOT
