server:
  port: ${API_GATEWAY_PORT:8085}

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: customer-service
              uri: lb://customer-service
              predicates:
                - Path=/customers/**
            - id: account-service
              uri: lb://account-service
              predicates:
                - Path=/accounts/**

eureka:
  client:
    enabled: ${EUREKA_CLIENT_ENABLED:true}
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

info:
  app:
    name: api-gateway
    description: API gateway for routing external requests to internal banking services
    version: 0.0.1-SNAPSHOT
